title: Mahfuza's Blog
author: Mahfuza Khatun @mkhtu1
email: mkhatun.ms@gmail.com
description: > # this means to ignore newlines until "baseurl:"
 This is one of my first blog posts to check how it works, doing as leanring each steps. It seems fun!
# social links
twitter_username: tinytinydots # DO NOT include the @ character, or else the build will fail!
github_username:  mkhatu1 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
